### ISSUE TITLE
NullPointerException when generating FTA

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#107]
When trying to generate the FTA for the ARP4761 model on the example repository, I got a NPE.
Try to generate the FTA for the system wbs.ima in the simple directory. Choose the error UnannunciatedBrakingLoss in the model.

org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=0, size=0
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
	at org.osate.xtext.aadl2.errormodel.util.EM2TypeSetUtil.contains(EM2TypeSetUtil.java:256)
	at org.osate.xtext.aadl2.errormodel.util.EM2TypeSetUtil.contains(EM2TypeSetUtil.java:329)
	at org.osate.xtext.aadl2.errormodel.util.EM2TypeSetUtil.contains(EM2TypeSetUtil.java:111)
	at org.osate.xtext.aadl2.errormodel.util.EM2TypeSetUtil.contains(EM2TypeSetUtil.java:169)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.getTargetType(PropagationGraphBackwardTraversal.java:120)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseOutgoingErrorPropagation(PropagationGraphBackwardTraversal.java:71)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseIncomingErrorPropagation(PropagationGraphBackwardTraversal.java:396)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:366)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseErrorBehaviorState(PropagationGraphBackwardTraversal.java:200)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.handleOutgoingErrorPropagationCondition(PropagationGraphBackwardTraversal.java:140)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseOutgoingErrorPropagation(PropagationGraphBackwardTraversal.java:74)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseIncomingErrorPropagation(PropagationGraphBackwardTraversal.java:396)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:366)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseErrorBehaviorState(PropagationGraphBackwardTraversal.java:200)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseCompositeErrorState(PropagationGraphBackwardTraversal.java:436)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:330)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:283)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:228)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseCompositeErrorState(PropagationGraphBackwardTraversal.java:429)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:330)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:252)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:228)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseCompositeErrorState(PropagationGraphBackwardTraversal.java:429)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:330)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:252)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:252)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:228)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseCompositeErrorState(PropagationGraphBackwardTraversal.java:429)
	at org.osate.aadl2.errormodel.emfta.fta.EMFTAGenerator.getEmftaModel(EMFTAGenerator.java:94)
	at org.osate.aadl2.errormodel.emfta.actions.EMFTAAction.doAaxlAction(EMFTAAction.java:180)
	at org.osate.ui.actions.AbstractAaxlAction.processAaxlAction(AbstractAaxlAction.java:528)
	at org.osate.ui.actions.AbstractAaxlAction.actionBody(AbstractAaxlAction.java:236)
	at org.osate.ui.actions.AaxlReadOnlyActionAsJob$ActionAsJob.runInWorkspace(AaxlReadOnlyActionAsJob.java:136)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by reteprelief** [comment]
Fixed.
