### ISSUE TITLE
Other NPE when generating FTA

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#108]
When trying to generate a FTA for a basic system, I got another NPE. See the following trace below. The model is error-model/fault-tree/redundant.aadl on the example repository.

Julien.

preProcessIncomingErrorPropagation thr propagation valuein2
java.lang.NullPointerException
	at org.osate.aadl2.errormodel.emfta.fta.EMFTAGenerator.postProcessErrorFlows(EMFTAGenerator.java:479)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseOutgoingErrorPropagation(PropagationGraphBackwardTraversal.java:103)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseIncomingErrorPropagation(PropagationGraphBackwardTraversal.java:396)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseOutgoingErrorPropagation(PropagationGraphBackwardTraversal.java:88)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseIncomingErrorPropagation(PropagationGraphBackwardTraversal.java:396)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:366)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseErrorBehaviorState(PropagationGraphBackwardTraversal.java:200)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseCompositeErrorState(PropagationGraphBackwardTraversal.java:436)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:330)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:228)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseCompositeErrorState(PropagationGraphBackwardTraversal.java:429)
	at org.osate.aadl2.errormodel.emfta.fta.EMFTAGenerator.getEmftaModel(EMFTAGenerator.java:94)
	at org.osate.aadl2.errormodel.emfta.actions.EMFTAAction.doAaxlAction(EMFTAAction.java:180)
	at org.osate.ui.actions.AbstractAaxlAction.processAaxlAction(AbstractAaxlAction.java:528)
	at org.osate.ui.actions.AbstractAaxlAction.actionBody(AbstractAaxlAction.java:236)
	at org.osate.ui.actions.AaxlReadOnlyActionAsJob$ActionAsJob.runInWorkspace(AaxlReadOnlyActionAsJob.java:136)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by reteprelief** [comment]
Fixed.
