### ISSUE TITLE
NullPointerException when getting subclause

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#55]
When using the emv2 tools, I got the following backtrace.

java.lang.NullPointerException
	at org.osate.xtext.aadl2.errormodel.util.EMV2Util.getAllContainingClassifierEMV2Subclauses(EMV2Util.java:142)
	at org.osate.xtext.aadl2.errormodel.util.EMV2Util.hasComponentErrorBehaviorStates(EMV2Util.java:2199)
	at org.osate.xtext.aadl2.errormodel.util.EMV2Util.hasComponentErrorBehaviorStates(EMV2Util.java:2195)
	at org.osate.xtext.aadl2.errormodel.util.EMV2Util$3.suchThat(EMV2Util.java:2270)
	at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.process(ForAllElement.java:271)
	at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.processPreOrderComponentInstance(ForAllElement.java:634)
	at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.processPreOrderComponentInstance(ForAllElement.java:639)
	at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.processPreOrderComponentInstance(ForAllElement.java:639)
	at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.processPreOrderComponentInstance(ForAllElement.java:639)
	at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.processPreOrderComponentInstance(ForAllElement.java:639)
	at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.processPreOrderComponentInstance(ForAllElement.java:639)
	at org.osate.aadl2.modelsupport.modeltraversal.ForAllElement.processPreOrderComponentInstance(ForAllElement.java:639)
	at org.osate.xtext.aadl2.errormodel.util.EMV2Util.getComponentInstancesWithComponentErrorBehaviorStates(EMV2Util.java:2273)
	at org.osate.aadl2.errormodel.analysis.actions.FTAAction.processRootSystem(FTAAction.java:85)
	at org.osate.aadl2.errormodel.analysis.actions.FTAAction.doAaxlAction(FTAAction.java:141)
	at org.osate.ui.actions.AbstractAaxlAction.processAaxlAction(AbstractAaxlAction.java:529)
	at org.osate.ui.actions.AbstractAaxlAction.actionBody(AbstractAaxlAction.java:234)
	at org.osate.ui.actions.AaxlReadOnlyActionAsJob$ActionAsJob.runInWorkspace(AaxlReadOnlyActionAsJob.java:134)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

**Comment by reteprelief** [comment]
addressed.
